name: MyStats
api: [3.0.0-ALPHA7, 4.0.0]
main: MyStats\MyStats
version: 1.4.0
author: CzechMPDevs
authors: [GamakCZ]
description: ScoreboardStats plugin ported to PMMP

commands:
  stats:
    description: Displays player s stats
    aliases: [ms, mstats, mys]

permissions:
  ms.cmd.stats:
    default: true
    description: Permission for /stats
