name: MyStats
api: [3.0.0-ALPHA7, 4.0.0]
main: MyStats\MyStats
version: 1.4.0 [BETA 2]
author: GamakCZ
description: ScoreboardStats plugin

commands:
  stats:
    description: Displays player s stats
    aliases: [ms, mstats, mys]

permissions:
  ms.cmd.stats:
    default: true
    description: Permission for /stats
