name: MyStats
api: [3.0.0-ALPHA7]
main: MyStats\MyStats
version: 1.4.1 [BETA]
author: CzechMPDevs
authors: [GamakCZ]
description: ScoreboardStats plugin ported to PocketMine

commands:
  stats:
    description: Displays player s stats
    aliases: [ms, mstats, mys]

permissions:
  ms.cmd.stats:
    default: true
    description: Permission for /stats
