name: MyStats
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
main: MyStats\MyStats
version: 1.4.4
author: CzechMPDevs
authors: [GamakCZ]
description: ScoreboardStats plugin ported to PocketMine
load: STARTUP

permissions:
  ms.cmd.stats:
    default: true
    description: Permission for /stats
