name: MyStats
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
main: mystats\MyStats
version: 1.4.5
author: CzechMPDevs
authors: [GamakCZ]
description: ScoreboardStats plugin ported to PocketMine
website: https://github.com/CzechPMDevs/MyStats
load: STARTUP

permissions:
  ms.cmd.stats:
    default: true
    description: Permission for /stats
