name: MyStats
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8]
main: MyStats\MyStats
version: 1.4.1
author: CzechMPDevs
authors: [GamakCZ]
description: ScoreboardStats plugin ported to PocketMine

permissions:
  ms.cmd.stats:
    default: true
    description: Permission for /stats
